services:
  postgres:
    container_name: rs-db
    image: newalexey/rs-home-library-pstgrs:latest
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: '${DB_PORT}'
      POSTGRES_USER: '${DB_USER_NAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '${DB_EXPOSE_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

  nest-app:
    container_name: rs-app
    image: newalexey/rs-home-library-app:latest
    env_file:
      - .env
    environment:
      DB_HOST: '${DB_HOST}'
    ports:
      - '${PORT}:${PORT}'
    build:
      context: .
    develop:
      watch:
        - path: ./src
          action: sync+restart
          target: /app/src
          ignore:
            - node_modules
    depends_on:
      - postgres
    restart: always
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge
    name: 'my-network'
